config/routes.rb
Rails.application.routes.draw do
  resources :compras
  get 'seguros/detail'
  resources :soatseguros
  resources :seguros
  resources :polizas
  resources :users
  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/poliza.rb
class Poliza < ApplicationRecord
end

app/controllers/polizas_controller.rb
class PolizasController < ApplicationController
  before_action :set_poliza, only: [:show, :edit, :update, :destroy]

  # GET /polizas
  # GET /polizas.json
  def index
    @polizas = Poliza.all
  end

  # GET /polizas/1
  # GET /polizas/1.json
  def show
  end

  # GET /polizas/new
  def new
    @poliza = Poliza.new
  end

  # GET /polizas/1/edit
  def edit
  end

  # POST /polizas
  # POST /polizas.json
  def create
    @poliza = Poliza.new(poliza_params)

    respond_to do |format|
      if @poliza.save
        format.html { redirect_to @poliza, notice: 'Poliza was successfully created.' }
        format.json { render :show, status: :created, location: @poliza }
      else
        format.html { render :new }
        format.json { render json: @poliza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polizas/1
  # PATCH/PUT /polizas/1.json
  def update
    respond_to do |format|
      if @poliza.update(poliza_params)
        format.html { redirect_to @poliza, notice: 'Poliza was successfully updated.' }
        format.json { render :show, status: :ok, location: @poliza }
      else
        format.html { render :edit }
        format.json { render json: @poliza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polizas/1
  # DELETE /polizas/1.json
  def destroy
    @poliza.destroy
    respond_to do |format|
      format.html { redirect_to polizas_url, notice: 'Poliza was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poliza
      @poliza = Poliza.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poliza_params
      params.require(:poliza).permit(:name)
    end
end

app/helpers/polizas_helper.rb
module PolizasHelper
end

app/views/polizas/_form.html.erb
<%= simple_form_for(@poliza) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/polizas/edit.html.erb
<h1>Editing Poliza</h1>

<%= render 'form', poliza: @poliza %>

<%= link_to 'Show', @poliza %> |
<%= link_to 'Back', polizas_path %>

app/views/polizas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Polizas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @polizas.each do |poliza| %>
      <tr>
        <td><%= poliza.name %></td>
        <td><%= link_to 'Show', poliza %></td>
        <td><%= link_to 'Edit', edit_poliza_path(poliza) %></td>
        <td><%= link_to 'Destroy', poliza, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Poliza', new_poliza_path %>

app/views/polizas/new.html.erb
<h1>New Poliza</h1>

<%= render 'form', poliza: @poliza %>

<%= link_to 'Back', polizas_path %>

app/views/polizas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @poliza.name %>
</p>

<%= link_to 'Edit', edit_poliza_path(@poliza) %> |
<%= link_to 'Back', polizas_path %>