config/routes.rb
Rails.application.routes.draw do
  resources :compras
  get 'seguros/detail'
  resources :soatseguros
  resources :seguros
  resources :polizas
  resources :users
  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/soatseguro.rb
class Soatseguro < ApplicationRecord
end

app/controllers/soatseguros_controller.rb
class SoatsegurosController < ApplicationController
  before_action :set_soatseguro, only: [:show, :edit, :update, :destroy]

  # GET /soatseguros
  # GET /soatseguros.json
  def index
    @soatseguros = Soatseguro.all
  end

  # GET /soatseguros/1
  # GET /soatseguros/1.json
  def show
  end

  # GET /soatseguros/new
  def new
    @soatseguro = Soatseguro.new
  end

  # GET /soatseguros/1/edit
  def edit
  end

  # POST /soatseguros
  # POST /soatseguros.json
  def create
    @soatseguro = Soatseguro.new(soatseguro_params)

    respond_to do |format|
      if @soatseguro.save
        format.html { redirect_to @soatseguro, notice: 'Soatseguro was successfully created.' }
        format.json { render :show, status: :created, location: @soatseguro }
      else
        format.html { render :new }
        format.json { render json: @soatseguro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /soatseguros/1
  # PATCH/PUT /soatseguros/1.json
  def update
    respond_to do |format|
      if @soatseguro.update(soatseguro_params)
        format.html { redirect_to @soatseguro, notice: 'Soatseguro was successfully updated.' }
        format.json { render :show, status: :ok, location: @soatseguro }
      else
        format.html { render :edit }
        format.json { render json: @soatseguro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /soatseguros/1
  # DELETE /soatseguros/1.json
  def destroy
    @soatseguro.destroy
    respond_to do |format|
      format.html { redirect_to soatseguros_url, notice: 'Soatseguro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_soatseguro
      @soatseguro = Soatseguro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def soatseguro_params
      params.require(:soatseguro).permit(:Placa, :del, :vehiculo, :Fecha, :inicio, :vigencia, :Fecha, :fin, :vigencia, :Numero, :pasajeros, :Cilindraje, :Clase, :Toneladas, :Edad, :Precio)
    end
end

app/helpers/soatseguros_helper.rb
module SoatsegurosHelper
end

app/views/soatseguros/_form.html.erb
<%= simple_form_for(@soatseguro) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :Placa %>
    <%= f.input :del %>
    <%= f.input :vehiculo %>
    <%= f.input :Fecha %>
    <%= f.input :inicio %>
    <%= f.input :vigencia %>
    <%= f.input :Fecha %>
    <%= f.input :fin %>
    <%= f.input :vigencia %>
    <%= f.input :Numero %>
    <%= f.input :pasajeros %>
    <%= f.input :Cilindraje %>
    <%= f.input :Clase %>
    <%= f.input :Toneladas %>
    <%= f.input :Edad %>
    <%= f.input :Precio %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/soatseguros/edit.html.erb
<h1>Editing Soatseguro</h1>

<%= render 'form', soatseguro: @soatseguro %>

<%= link_to 'Show', @soatseguro %> |
<%= link_to 'Back', soatseguros_path %>

app/views/soatseguros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Soatseguros</h1>

<table>
  <thead>
    <tr>
      <th>Placa</th>
      <th>Del</th>
      <th>Vehiculo</th>
      <th>Fecha</th>
      <th>Inicio</th>
      <th>Vigencia</th>
      <th>Fecha</th>
      <th>Fin</th>
      <th>Vigencia</th>
      <th>Numero</th>
      <th>Pasajeros</th>
      <th>Cilindraje</th>
      <th>Clase</th>
      <th>Toneladas</th>
      <th>Edad</th>
      <th>Precio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @soatseguros.each do |soatseguro| %>
      <tr>
        <td><%= soatseguro.Placa %></td>
        <td><%= soatseguro.del %></td>
        <td><%= soatseguro.vehiculo %></td>
        <td><%= soatseguro.Fecha %></td>
        <td><%= soatseguro.inicio %></td>
        <td><%= soatseguro.vigencia %></td>
        <td><%= soatseguro.Fecha %></td>
        <td><%= soatseguro.fin %></td>
        <td><%= soatseguro.vigencia %></td>
        <td><%= soatseguro.Numero %></td>
        <td><%= soatseguro.pasajeros %></td>
        <td><%= soatseguro.Cilindraje %></td>
        <td><%= soatseguro.Clase %></td>
        <td><%= soatseguro.Toneladas %></td>
        <td><%= soatseguro.Edad %></td>
        <td><%= soatseguro.Precio %></td>
        <td><%= link_to 'Show', soatseguro %></td>
        <td><%= link_to 'Edit', edit_soatseguro_path(soatseguro) %></td>
        <td><%= link_to 'Destroy', soatseguro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Soatseguro', new_soatseguro_path %>

app/views/soatseguros/new.html.erb
<h1>New Soatseguro</h1>

<%= render 'form', soatseguro: @soatseguro %>

<%= link_to 'Back', soatseguros_path %>

app/views/soatseguros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Placa:</strong>
  <%= @soatseguro.Placa %>
</p>

<p>
  <strong>Del:</strong>
  <%= @soatseguro.del %>
</p>

<p>
  <strong>Vehiculo:</strong>
  <%= @soatseguro.vehiculo %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @soatseguro.Fecha %>
</p>

<p>
  <strong>Inicio:</strong>
  <%= @soatseguro.inicio %>
</p>

<p>
  <strong>Vigencia:</strong>
  <%= @soatseguro.vigencia %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @soatseguro.Fecha %>
</p>

<p>
  <strong>Fin:</strong>
  <%= @soatseguro.fin %>
</p>

<p>
  <strong>Vigencia:</strong>
  <%= @soatseguro.vigencia %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @soatseguro.Numero %>
</p>

<p>
  <strong>Pasajeros:</strong>
  <%= @soatseguro.pasajeros %>
</p>

<p>
  <strong>Cilindraje:</strong>
  <%= @soatseguro.Cilindraje %>
</p>

<p>
  <strong>Clase:</strong>
  <%= @soatseguro.Clase %>
</p>

<p>
  <strong>Toneladas:</strong>
  <%= @soatseguro.Toneladas %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @soatseguro.Edad %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @soatseguro.Precio %>
</p>

<%= link_to 'Edit', edit_soatseguro_path(@soatseguro) %> |
<%= link_to 'Back', soatseguros_path %>