config/routes.rb
Rails.application.routes.draw do
  resources :compras
  get 'seguros/detail'
  resources :soatseguros
  resources :seguros
  resources :polizas
  resources :users
  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/compra.rb
class Compra < ApplicationRecord
end

app/controllers/compras_controller.rb
class ComprasController < ApplicationController
  before_action :set_compra, only: [:show, :edit, :update, :destroy]

  # GET /compras
  # GET /compras.json
  def index
    @compras = Compra.all
  end

  # GET /compras/1
  # GET /compras/1.json
  def show
  end

  # GET /compras/new
  def new
    @compra = Compra.new
  end

  # GET /compras/1/edit
  def edit
  end

  # POST /compras
  # POST /compras.json
  def create
    @compra = Compra.new(compra_params)

    respond_to do |format|
      if @compra.save
        format.html { redirect_to @compra, notice: 'Compra was successfully created.' }
        format.json { render :show, status: :created, location: @compra }
      else
        format.html { render :new }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compras/1
  # PATCH/PUT /compras/1.json
  def update
    respond_to do |format|
      if @compra.update(compra_params)
        format.html { redirect_to @compra, notice: 'Compra was successfully updated.' }
        format.json { render :show, status: :ok, location: @compra }
      else
        format.html { render :edit }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compras/1
  # DELETE /compras/1.json
  def destroy
    @compra.destroy
    respond_to do |format|
      format.html { redirect_to compras_url, notice: 'Compra was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compra
      @compra = Compra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def compra_params
      params.require(:compra).permit(:Numero_tarjeta, :Nombre_titular, :Fecha_de_vencimiento_tarjeta, :Codigo_seguridad, :Numero_cuotas, :Placa_asociada, :id_seguro)
    end
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/views/compras/_form.html.erb
<%= simple_form_for(@compra) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :Numero_tarjeta %>
    <%= f.input :Nombre_titular %>
    <%= f.input :Fecha_de_vencimiento_tarjeta %>
    <%= f.input :Codigo_seguridad %>
    <%= f.input :Numero_cuotas %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/compras/edit.html.erb
<h1>Editing Compra</h1>

<%= render 'form', compra: @compra %>

<%= link_to 'Show', @compra %> |
<%= link_to 'Back', compras_path %>

app/views/compras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Compras</h1>

<table>
  <thead>
    <tr>
      <th>Numero tarjeta</th>
      <th>Nombre titular</th>
      <th>Fecha de vencimiento tarjeta</th>
      <th>Codigo seguridad</th>
      <th>Numero cuotas</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @compras.each do |compra| %>
      <tr>
        <td><%= compra.Numero_tarjeta %></td>
        <td><%= compra.Nombre_titular %></td>
        <td><%= compra.Fecha_de_vencimiento_tarjeta %></td>
        <td><%= compra.Codigo_seguridad %></td>
        <td><%= compra.Numero_cuotas %></td>
        <td><%= link_to 'Show', compra %></td>
        <td><%= link_to 'Edit', edit_compra_path(compra) %></td>
        <td><%= link_to 'Destroy', compra, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Compra', new_compra_path %>

app/views/compras/new.html.erb
<h4>New Compra</h4>

<%= render 'form', compra: @compra %>

<%= link_to 'Back', compras_path %>

app/views/compras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numero tarjeta:</strong>
  <%= @compra.Numero_tarjeta %>
</p>

<p>
  <strong>Nombre titular:</strong>
  <%= @compra.Nombre_titular %>
</p>

<p>
  <strong>Fecha de vencimiento tarjeta:</strong>
  <%= @compra.Fecha_de_vencimiento_tarjeta %>
</p>

<p>
  <strong>Codigo seguridad:</strong>
  <%= @compra.Codigo_seguridad %>
</p>

<p>
  <strong>Numero cuotas:</strong>
  <%= @compra.Numero_cuotas %>
</p>

<%= link_to 'Edit', edit_compra_path(@compra) %> |
<%= link_to 'Back', compras_path %>